### ISSUE TITLE
idk if u see this

### ISSUE THREAD

**Issue by stampe99** [Anomia-s/listen-moe#1]
but it says my ip adress got blacklisted from discord so yeah

**Comment by bluefield-creator** [comment]
Hello, can you send a screenshot?

**Comment by bluefield-creator** [comment]
Also Discord is apparently half-down

**Comment by bluefield-creator** [comment]
![image](https://user-images.githubusercontent.com/48862659/157312033-cb9b1071-def7-4a68-901f-b480283e56e1.png)

**Comment by bluefield-creator** [comment]
![image](https://user-images.githubusercontent.com/48862659/157312097-0bf8d3d3-218a-4337-968b-84e1021b9f17.png)

**Comment by stampe99** [comment]
It says "Your IP Adress is currently blacklisted from our CloudFare" only on phone, on pc i cant even press login.

**Comment by bluefield-creator** [comment]
> It says "Your IP Adress is currently blacklisted from our CloudFare"

did you spam reload or something?

**Comment by stampe99** [comment]
> > It says "Your IP Adress is currently blacklisted from our CloudFare"
> 
> did you spam reload or something?

i dont think so, but however when i was inside my account i restarted it about 4 times

**Comment by bluefield-creator** [comment]
> > > It says "Your IP Adress is currently blacklisted from our CloudFare"
> > 
> > 
> > did you spam reload or something?
> 
> i dont think so, but however when i was inside my account i restarted it about 4 times

Just wait.

**Comment by stampe99** [comment]
> > > > It says "Your IP Adress is currently blacklisted from our CloudFare"
> > > 
> > > 
> > > did you spam reload or something?
> > 
> > 
> > i dont think so, but however when i was inside my account i restarted it about 4 times
> 
> Just wait.

alright
